### ISSUE TITLE
mulmxP to mxalgebra?

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/real-closed#1]
https://github.com/math-comp/real-closed/blob/8f5785134a6f86aa53aaee89a733c7a4eec0538f/theories/complex.v#L690-L691

Wouldn't this lemma fit into mxalgebra.v?

**Comment by CohenCyril** [comment]
Yes, I am preparing one more pull request for all the matrices theorms I would like to backport like this.

**Comment by affeldt-aist** [comment]
Is this essentially `Section extramx.`?

**Comment by CohenCyril** [comment]
@affeldt-aist yes it is

**Comment by CohenCyril** [comment]
Closed in math-comp/math-comp#577
