### ISSUE TITLE
Broken on Coq bench

### ISSUE THREAD

**Issue by SkySkimmer** [math-comp/real-closed#4]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/567/console
```
File "./theories/complex.v", line 1245, characters 36-57:
Error: The reference closed_fields_QEMixin was not found in the current
environment.
```
I guess some import changed at some point?

**Comment by drouhling** [comment]
This comes from a change of name in the field package (`fields` became `field`).

This should be fixed by #5
