### ISSUE TITLE
Support mathcomp 1.15.0

### ISSUE THREAD

**Issue by SnarkBoojum** [math-comp/real-closed#46]
I just tried to update ssreflect in Debian, and it looks like there are problems. I'll try to dig a little in the coming days. Here are the [build logs ](https://buildd.debian.org/status/package.php?p=mathcomp-real-closed&suite=sid).

**Comment by affeldt-aist** [comment]
> Sigh... it's fixed in 1.1.3 already. Sorry for the noise.

No problem. Thank you for your work.
